export const languages={en:"English",hi:"हिन्दी",as:"অসমীয়া",bn:"বাংলা",mni:"ꯃꯤꯇꯩ ꯂꯣꯟ"};
const rows={
appName:["SmritiAI","SmritiAI","SmritiAI","SmritiAI","SmritiAI"],brandSubtitle:["Memory · Care","स्मृति · देखभाल","স্মৃতি · যত্ন","স্মৃতি · যত্ন","ꯅꯤꯡꯁꯤꯡ · ꯌꯦꯡꯁꯤꯟꯕ"],language:["Language","भाषा","ভাষা","ভাষা","ꯂꯣꯟ"],home:["Home","होम","মুখ্যপৃষ্ঠা","হোম","ꯌꯨꯝ"],games:["Games","खेल","খেল","খেলা","ꯁꯥꯟꯅꯕ"],reminders:["Reminders","रिमाइंडर","সোঁৱৰাই দিয়া","স্মরণিকা","ꯅꯤꯡꯁꯤꯡꯍꯟꯕ"],companion:["Companion","साथी","সহচৰ","সঙ্গী","ꯃꯔꯨꯞ"],caregiver:["Caregiver","देखभालकर्ता","যত্ন লওঁতা","পরিচর্যাকারী","ꯌꯦꯡꯁꯤꯟꯕ"],patient:["Patient","रोगी","ব্যক্তি","রোগী","ꯂꯥꯏꯕꯥꯛ"],signOut:["Sign out","साइन आउट","ছাইন আউট","সাইন আউট","ꯁꯥꯏꯟ ꯑꯥꯎꯠ"],sync:["Sync","सिंक","ছিংক","সিঙ্ক","ꯁꯤꯡꯛ"],voice:["Voice help","आवाज़ सहायता","কণ্ঠ সহায়","ভয়েস সহায়তা","ꯈꯣꯟꯖꯦꯜ ꯃꯇꯦꯡ"],
gentleSupport:["Gentle daily support","स्नेहपूर्ण दैनिक सहारा","কোমল দৈনিক সহায়","কোমল দৈনন্দিন সহায়তা","ꯅꯤꯠꯌꯒꯤ ꯃꯇꯦꯡ"],heroTitle:["Every memory deserves a","हर स्मृति को चाहिए","প্ৰতিটো স্মৃতিৰ বাবে লাগে","প্রতিটি স্মৃতির প্রাপ্য","ꯅꯤꯡꯁꯤꯡ ꯈꯨꯗꯤꯡꯃꯛꯅ"],heroEmphasis:["familiar path home.","घर की परिचित राह।","ঘৰলৈ চিনাকি বাট।","ঘরে ফেরার পরিচিত পথ।","ꯌꯨꯝꯗ ꯍꯜꯂꯛꯄꯒꯤ ꯂꯝꯕꯤ꯫"],heroDescription:["Games, family moments, reminders and reassuring companionship for older adults and caregivers.","बुज़ुर्गों और देखभालकर्ताओं के लिए खेल, पारिवारिक पल, रिमाइंडर और साथ।","বয়োজ্যেষ্ঠ আৰু যত্ন লওঁতাসকলৰ বাবে খেল, পৰিয়ালৰ মুহূৰ্ত আৰু সোঁৱৰণী।","বয়স্ক মানুষ ও পরিচর্যাকারীদের জন্য খেলা, পারিবারিক মুহূর্ত ও স্মরণিকা।","ꯂꯥꯏꯕꯥꯛ ꯑꯃꯁꯨꯡ ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯁꯥꯟꯅꯕ, ꯏꯃꯨꯡ ꯑꯃꯁꯨꯡ ꯃꯇꯦꯡ꯫"],worksOffline:["Works offline","ऑफ़लाइन चलता है","অফলাইনতো চলে","অফলাইনে চলে","ꯑꯣꯐꯂꯥꯏꯟꯗ ꯊꯕꯛ ꯇꯧꯏ"],clearControls:["Large, clear controls","बड़े, स्पष्ट नियंत्रण","ডাঙৰ, স্পষ্ট নিয়ন্ত্ৰণ","বড়, স্পষ্ট নিয়ন্ত্রণ","ꯑꯆꯧꯕ ꯁꯦꯡꯕ ꯀꯟꯇ꯭ꯔꯣꯜ"],privateSpace:["Private family space","निजी पारिवारिक स्थान","ব্যক্তিগত পৰিয়ালৰ ঠাই","ব্যক্তিগত পারিবারিক স্থান","ꯏꯃꯨꯡꯒꯤ ꯑꯔꯣꯟꯕ ꯃꯐꯝ"],demo:["Try the guided demo","निर्देशित डेमो आज़माएँ","নিৰ্দেশিত ডেমো চাওক","নির্দেশিত ডেমো দেখুন","ꯂꯝꯖꯤꯡꯕ ꯗꯦꯃꯣ ꯌꯦꯡꯕ"],login:["Sign in","साइन इन","ছাইন ইন","সাইন ইন","ꯁꯥꯏꯟ ꯏꯟ"],register:["Create family account","परिवार खाता बनाएँ","পৰিয়ালৰ একাউণ্ট খোলক","পারিবারিক অ্যাকাউন্ট তৈরি করুন","ꯏꯃꯨꯡꯒꯤ ꯑꯦꯀꯥꯎꯟꯠ ꯁꯦꯝꯕ"],install:["Install app","ऐप इंस्टॉल करें","এপ ইনষ্টল কৰক","অ্যাপ ইনস্টল করুন","ꯑꯦꯞ ꯏꯟꯁꯇꯣꯜ ꯇꯧꯕ"],
email:["Email address","ईमेल पता","ইমেইল ঠিকনা","ইমেল ঠিকানা","ꯏꯃꯦꯜ ꯑꯦꯗ꯭ꯔꯦꯁ"],password:["Password","पासवर्ड","পাছৱৰ্ড","পাসওয়ার্ড","ꯄꯥꯁꯋꯥꯔꯗ"],patientName:["Patient's name","रोगी का नाम","ব্যক্তিৰ নাম","রোগীর নাম","ꯂꯥꯏꯕꯥꯛꯀꯤ ꯃꯃꯤꯡ"],caregiverName:["Caregiver name","देखभालकर्ता का नाम","যত্ন লওঁতাৰ নাম","পরিচর্যাকারীর নাম","ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯃꯃꯤꯡ"],pin:["Caregiver PIN","देखभालकर्ता PIN","যত্ন লওঁতাৰ PIN","পরিচর্যাকারীর PIN","ꯌꯦꯡꯁꯤꯟꯕꯒꯤ PIN"],welcomeBack:["Welcome back. Your family space stays on this device.","फिर स्वागत है। आपका पारिवारिक स्थान इस डिवाइस पर है।","পুনৰ স্বাগতম। আপোনাৰ পৰিয়ালৰ ঠাই এই ডিভাইচত আছে।","আবার স্বাগতম। আপনার পারিবারিক স্থান এই ডিভাইসে আছে।","ꯑꯃꯨꯛ ꯇꯥꯔꯛꯄꯗ ꯇꯔꯥꯝꯅ ꯑꯣꯛꯆꯔꯤ꯫"],connecting:["Connecting securely…","सुरक्षित रूप से जुड़ रहा है…","সুৰক্ষিতভাৱে সংযোগ কৰা হৈছে…","নিরাপদভাবে সংযোগ হচ্ছে…","ꯉꯥꯛꯂꯕ ꯃꯑꯣꯡꯗ ꯁꯝꯅꯔꯤ…"],
friend:["Friend","मित्र","বন্ধু","বন্ধু","ꯃꯔꯨꯞ"],greeting:["Namaste, {name}.","नमस्ते, {name}।","নমস্কাৰ, {name}।","নমস্কার, {name}।","ꯈꯨꯔꯨꯝꯖꯔꯤ, {name}꯫"],whatDo:["What would you like to do?","आप क्या करना चाहेंगे?","আপুনি কি কৰিব বিচাৰে?","আপনি কী করতে চান?","ꯅꯍꯥꯛ ꯀꯔꯤ ꯇꯧꯅꯤꯡꯕꯒꯦ?"],wellness:["Wellness","स्वास्थ्य","সুস্থতা","সুস্থতা","ꯐꯕ ꯂꯩꯕ"],playGame:["Play a game","खेल खेलें","খেল খেলক","খেলা খেলুন","ꯁꯥꯟꯅꯕ ꯑꯃ ꯁꯥꯟꯅꯧ"],seeReminders:["See reminders","रिमाइंडर देखें","সোঁৱৰাই দিয়াবোৰ চাওক","স্মরণিকা দেখুন","ꯅꯤꯡꯁꯤꯡꯍꯟꯕ ꯌꯦꯡꯕ"],dailyTasks:["Today's routine","आज की दिनचर्या","আজিৰ দৈনন্দিন কাম","আজকের রুটিন","ꯉꯁꯤꯒꯤ ꯅꯤꯠꯌ ꯊꯕꯛ"],medicine:["Take medicine","दवा लें","ঔষধ লওক","ওষুধ নিন","ꯂꯥꯏ ꯆꯥꯕ"],water:["Drink water","पानी पिएँ","পানী খাওক","জল পান করুন","ꯏꯁꯤꯡ ꯊꯛꯄ"],exercise:["Gentle exercise","हल्का व्यायाम","কোমল ব্যায়াম","হালকা ব্যায়াম","ꯂꯤꯟꯁꯤꯡꯕ ꯑꯦꯛꯁꯔꯁꯥꯏꯖ"],activity:["Daily activity","दैनिक गतिविधि","দৈনিক কাম","দৈনন্দিন কাজ","ꯅꯤꯠꯌ ꯊꯕꯛ"],mood:["Mood","मूड","মনোভাৱ","মেজাজ","ꯊꯧꯔꯝ"],streak:["day streak","दिन की निरंतरता","দিনৰ ধাৰাবাহিকতা","দিনের ধারাবাহিকতা","ꯅꯨꯃꯤꯠ ꯃꯊꯪ"],emergency:["Emergency help","आपात सहायता","জৰুৰী সহায়","জরুরি সাহায্য","ꯑꯊꯨꯕ ꯃꯇꯦꯡ"],notDiagnosis:["Engagement guidance only — not a diagnosis or medical advice.","केवल सहभागिता मार्गदर्शन — निदान या चिकित्सा सलाह नहीं।","কেৱল অংশগ্ৰহণৰ সহায় — ৰোগ নিৰ্ণয় বা চিকিৎসা পৰামৰ্শ নহয়।","শুধু অংশগ্রহণ নির্দেশনা — রোগ নির্ণয় বা চিকিৎসা পরামর্শ নয়।","ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯃꯇꯦꯡꯈꯛꯇꯃꯛ꯫"],
play:["Play","खेलें","খেলক","খেলুন","ꯁꯥꯟꯅꯕ"],back:["Back","वापस","পিছলৈ","ফিরুন","ꯍꯟꯕ"],easy:["Easy","आसान","সহজ","সহজ","ꯂꯥꯏꯕ"],medium:["Medium","मध्यम","মধ্যম","মাঝারি","ꯃꯌꯥꯏ"],hard:["Hard","कठिन","কঠিন","কঠিন","ꯑꯔꯨꯕ"],start:["Start game","खेल शुरू करें","খেল আৰম্ভ কৰক","খেলা শুরু করুন","ꯁꯥꯟꯅꯕ ꯍꯧꯕ"],wellDone:["Well done","बहुत अच्छा","বঢ়িয়া হৈছে","খুব ভালো","ꯌꯥꯝꯅ ꯐꯔꯦ"],accuracy:["accuracy","सटीकता","শুদ্ধতা","নির্ভুলতা","ꯆꯨꯝꯕ"],playAgain:["Play again","फिर खेलें","পুনৰ খেলক","আবার খেলুন","ꯑꯃꯨꯛ ꯁꯥꯟꯅꯕ"],allGames:["All games","सभी खेल","সকলো খেল","সব খেলা","ꯁꯥꯟꯅꯕ ꯄꯨꯝꯅꯃꯛ"],
gameMemoryTitle:["Memory Match","स्मृति मिलान","স্মৃতি মিলোৱা","স্মৃতি মিল","ꯅꯤꯡꯁꯤꯡ ꯆꯥꯟꯅꯍꯟꯕ"],gameObjectsTitle:["Object Recall","वस्तु स्मरण","বস্তু স্মৰণ","বস্তু স্মরণ","ꯄꯣꯠꯂꯝ ꯅꯤꯡꯁꯤꯡꯕ"],gameRoutineTitle:["Daily Routine","दैनिक दिनचर्या","দৈনিক কাম","দৈনন্দিন রুটিন","ꯅꯤꯠꯌ ꯊꯕꯛ"],gamePatternTitle:["Pattern Paths","पैटर्न पथ","আৰ্হিৰ বাট","প্যাটার্ন পথ","ꯃꯑꯣꯡꯒꯤ ꯂꯝꯕꯤ"],gameFamilyTitle:["Family Faces","परिवार के चेहरे","পৰিয়ালৰ মুখ","পরিবারের মুখ","ꯏꯃꯨꯡꯒꯤ ꯃꯥꯌ"],gameSequenceTitle:["Sequence Memory","क्रम स्मृति","ক্ৰম স্মৃতি","ক্রম স্মৃতি","ꯃꯊꯪ ꯅꯤꯡꯁꯤꯡ"],
roundOf:["Round {current} of {total}","राउंड {current} / {total}","ৰাউণ্ড {current} / {total}","রাউন্ড {current} / {total}","ꯔꯥꯎꯟꯗ {current} / {total}"],chooseNext:["Choose the next item","अगली वस्तु चुनें","পৰৱৰ্তী বস্তু বাছক","পরের বস্তু বেছে নিন","ꯃꯊꯪꯒꯤ ꯄꯣꯠꯂꯝ ꯈꯜꯂꯨ"],who:["Who is this?","यह कौन है?","এয়া কোন?","ইনি কে?","ꯃꯁꯤ ꯀꯅꯥꯅꯣ?"],relationshipQ:["How are they related to you?","इनका आपसे क्या रिश्ता है?","তেওঁ আপোনাৰ কোন হয়?","তিনি আপনার কে হন?","ꯃꯍꯥꯛ ꯅꯍꯥꯛꯀꯤ ꯀꯔꯤ ꯃꯔꯤꯅꯣ?"],getReady:["Get ready","तैयार हो जाएँ","সাজু হওক","প্রস্তুত হন","ꯁꯦꯝ ꯁꯥꯕꯤꯌꯨ"],watchSequence:["Watch the sequence","क्रम देखें","ক্ৰমটো চাওক","ক্রমটি দেখুন","ꯃꯊꯪ ꯌꯦꯡꯕꯤꯌꯨ"],repeatSequence:["Now repeat it","अब दोहराएँ","এতিয়া পুনৰ কৰক","এখন আবার করুন","ꯍꯧꯖꯤꯛ ꯑꯃꯨꯛ ꯇꯧꯕꯤꯌꯨ"],yourProgress:["Your progress","आपकी प्रगति","আপোনাৰ অগ্ৰগতি","আপনার অগ্রগতি","ꯅꯍꯥꯛꯀꯤ ꯈꯨꯝꯃꯥꯡ"],
addReminder:["Add reminder","रिमाइंडर जोड़ें","সোঁৱৰণী যোগ কৰক","স্মরণিকা যোগ করুন","ꯅꯤꯡꯁꯤꯡꯍꯟꯕ ꯍꯥꯞꯆꯤꯟꯕ"],noReminders:["No reminders yet.","अभी कोई रिमाइंडर नहीं।","এতিয়াও কোনো সোঁৱৰণী নাই।","এখনও কোনো স্মরণিকা নেই।","ꯍꯧꯖꯤꯛ ꯅꯤꯡꯁꯤꯡꯍꯟꯕ ꯂꯩꯇꯦ꯫"],complete:["Complete","पूरा करें","সম্পূৰ্ণ","সম্পূর্ণ","ꯂꯣꯏꯁꯤꯟꯕ"],snooze:["Snooze 10 min","10 मिनट टालें","১০ মিনিট পিছুৱাওক","১০ মিনিট পিছিয়ে দিন","ꯃꯤꯅꯤꯠ ১০ ꯊꯝꯕ"],edit:["Edit","संपादित करें","সম্পাদনা","সম্পাদনা","ꯁꯦꯝꯗꯣꯛꯄ"],delete:["Delete","हटाएँ","মচক","মুছুন","ꯃꯨꯠꯊꯠꯄ"],save:["Save","सहेजें","সংৰক্ষণ","সংরক্ষণ","ꯊꯝꯕ"],cancel:["Cancel","रद्द करें","বাতিল","বাতিল","ꯀꯛꯊꯠꯄ"],close:["Close","बंद करें","বন্ধ কৰক","বন্ধ করুন","ꯂꯣꯏꯁꯤꯟꯕ"],time:["Time","समय","সময়","সময়","ꯃꯇꯝ"],category:["Category","श्रेणी","শ্ৰেণী","বিভাগ","ꯀꯥꯡꯂꯨꯞ"],title:["Reminder","रिमाइंडर","সোঁৱৰণী","স্মরণিকা","ꯅꯤꯡꯁꯤꯡꯍꯟꯕ"],
analytics:["Progress & insights","प्रगति और जानकारी","অগ্ৰগতি আৰু তথ্য","অগ্রগতি ও তথ্য","ꯈꯨꯝꯃꯥꯡ ꯑꯃꯁꯨꯡ ꯋꯥꯔꯣꯜ"],report:["Download PDF report","PDF रिपोर्ट डाउनलोड करें","PDF প্ৰতিবেদন লওক","PDF রিপোর্ট ডাউনলোড করুন","PDF ꯔꯤꯄꯣꯔꯠ ꯂꯧꯕ"],alerts:["Care alerts","देखभाल चेतावनियाँ","যত্নৰ সতৰ্কবাণী","পরিচর্যা সতর্কতা","ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯄꯥꯎ"],achievements:["Achievements","उपलब्धियाँ","অৰ্জন","অর্জন","ꯃꯥꯏꯄꯥꯛꯄ"],familyMemories:["Family memories","पारिवारिक स्मृतियाँ","পৰিয়ালৰ স্মৃতি","পারিবারিক স্মৃতি","ꯏꯃꯨꯡꯒꯤ ꯅꯤꯡꯁꯤꯡ"],addFamily:["Add family member","परिवार सदस्य जोड़ें","পৰিয়ালৰ সদস্য যোগ কৰক","পরিবারের সদস্য যোগ করুন","ꯏꯃꯨꯡꯒꯤ ꯃꯤ ꯍꯥꯞꯆꯤꯟꯕ"],name:["Full name","पूरा नाम","সম্পূৰ্ণ নাম","পুরো নাম","ꯃꯄꯨꯡ ꯐꯥꯕ ꯃꯃꯤꯡ"],relationship:["Relationship","रिश्ता","সম্পৰ্ক","সম্পর্ক","ꯃꯔꯤ"],photo:["Photo","फ़ोटो","ফটো","ছবি","ꯐꯣꯇꯣ"],unlock:["Unlock","अनलॉक","খোলক","আনলক","ꯍꯥꯡꯗꯣꯛꯄ"],incorrectPin:["That PIN did not match.","PIN मेल नहीं खाया।","PIN মিল নাই।","PIN মেলেনি।","PIN ꯆꯥꯟꯅꯗꯦ꯫"],offline:["Offline — changes are safe","ऑफ़लाइन — बदलाव सुरक्षित हैं","অফলাইন — সলনিবোৰ সুৰক্ষিত","অফলাইন — পরিবর্তন নিরাপদ","ꯑꯣꯐꯂꯥꯏꯟ — ꯍꯣꯡꯗꯣꯛꯄ ꯉꯥꯛꯂꯦ"],
companionScope:["I can help with emotional wellbeing and everyday conversation, but I can’t help with coding or technical tasks. What is on your mind today?","मैं भावनात्मक भलाई और रोज़मर्रा की बातचीत में साथ दे सकता हूँ, लेकिन कोडिंग या तकनीकी काम में मदद नहीं कर सकता। आज आपके मन में क्या है?","মই মানসিক সুস্থতা আৰু দৈনন্দিন কথোপকথনত সংগ দিব পাৰোঁ, কিন্তু ক'ডিং বা কাৰিকৰী কামত সহায় কৰিব নোৱাৰোঁ। আজি আপোনাৰ মনত কি আছে?","আমি মানসিক সুস্থতা ও দৈনন্দিন কথোপকথনে সঙ্গ দিতে পারি, কিন্তু কোডিং বা প্রযুক্তিগত কাজে সাহায্য করতে পারি না। আজ আপনার মনে কী আছে?","ꯑꯩꯅ ꯋꯥꯈꯜꯒꯤ ꯐꯤꯕꯝ ꯑꯃꯁꯨꯡ ꯅꯨꯡꯉꯥꯏꯅ ꯋꯥꯔꯤ ꯁꯥꯟꯅꯕꯗ ꯃꯇꯦꯡ ꯄꯥꯡꯒꯅꯤ, ꯑꯗꯨꯕꯨ ꯀꯣꯗꯤꯡ ꯅꯠꯇ꯭ꯔꯒ ꯇꯦꯛꯅꯤꯀꯦꯜ ꯊꯕꯛꯇ ꯃꯇꯦꯡ ꯄꯥꯡꯗꯦ꯫"],
companionCrisis:["I’m really sorry you’re feeling this much pain. Please contact local emergency services now or stay with a trusted person who can help keep you safe. Use the SOS button to alert your caregiver. I can stay with you for a calm conversation, but I am not an emergency service.","मुझे दुख है कि आप इतना दर्द महसूस कर रहे हैं। अभी स्थानीय आपातकालीन सेवा से संपर्क करें या किसी भरोसेमंद व्यक्ति के साथ रहें। देखभालकर्ता को बताने के लिए SOS बटन दबाएँ। मैं शांत बातचीत में आपके साथ रह सकता हूँ, लेकिन मैं आपातकालीन सेवा नहीं हूँ।","আপুনি ইমান কষ্ট পাইছে বুলি জানি মোৰ দুখ লাগিছে। এতিয়াই স্থানীয় জৰুৰীকালীন সেৱাৰ সৈতে যোগাযোগ কৰক বা বিশ্বাসযোগ্য ব্যক্তিৰ লগত থাকক। যত্ন লওঁতাক জনাবলৈ SOS বুটাম ব্যৱহাৰ কৰক।","আপনি এতটা কষ্ট পাচ্ছেন জেনে আমি দুঃখিত। এখনই স্থানীয় জরুরি পরিষেবায় যোগাযোগ করুন বা বিশ্বাসযোগ্য কারও সঙ্গে থাকুন। পরিচর্যাকারীকে জানাতে SOS বোতাম ব্যবহার করুন।","ꯅꯍꯥꯛ ꯑꯁꯨꯛ ꯌꯥꯝꯅ ꯑꯋꯥꯕ ꯐꯥꯎꯔꯤꯕ ꯑꯗꯨꯒꯤꯗꯃꯛ ꯑꯩ ꯅꯨꯡꯉꯥꯏꯇꯕ ꯐꯥꯎꯏ꯫ ꯍꯧꯖꯤꯛ ꯂꯝꯒꯤ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯁꯔꯚꯤꯁꯇ ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ ꯑꯃꯁꯨꯡ SOS ꯕꯇꯟ ꯁꯤꯖꯤꯟꯅꯧ꯫"]
};
const codes=["en","hi","as","bn","mni"];
export const dictionaries=Object.fromEntries(codes.map((c,i)=>[c,Object.fromEntries(Object.entries(rows).map(([k,v])=>[k,v[i]]))]));
const generic={hi:"जानकारी",as:"তথ্য",bn:"তথ্য",mni:"ꯋꯥꯔꯣꯜ"};
const aliases={
  openCaregiver:"caregiver",returnPatient:"patient",syncData:"sync",skipContent:"home",smritiHome:"home",primaryNav:"home",preparing:"gentleSupport",
  oneFamilySpace:"familyMemories",setupAccount:"register",pinHelp:"pin",noAccount:"demo",internetNeeded:"offline",sampleMemory:"familyMemories",familyQuote:"familyMemories",fictionalDaughter:"relationshipDaughter",fictionalSon:"relationshipSon",fictionalGranddaughter:"relationshipGranddaughter",fictionalFamily:"familyMemories",
  simpleEnjoyable:"play",nothingDue:"noReminders",todayAt:"time",tapWhenDone:"dailyTasks",tapFace:"mood",routineUpdated:"dailyTasks",thanksMood:"mood",pressCaregiver:"caregiver",emergencyNote:"emergency",
  playEveryDay:"games",chooseGame:"games",gamesPlayed:"games",cognitiveActivity:"games",difficulty:"medium",takeYourTime:"play",completedGame:"wellDone",mistakeCount:"accuracy",nextLevel:"difficulty",comfortableRhythm:"reminders",remindersLead:"reminders",anyTime:"time",completed:"complete",undo:"back",gentlePrompt:"reminders",reminderUpdated:"reminders",snoozed:"snooze",deleteReminderQ:"delete",deleteNamed:"delete",reminderSaved:"save",
  listeningSpace:"companion",companionLead:"companion",memoryPrompts:"memory",festivalPrompt:"companion",childhoodPrompt:"companion",laughPrompt:"companion",mealPrompt:"companion",story:"companion",supportive:"companion",shareMemoryQ:"companion",companionPrompt:"companion",send:"companion",storyRequest:"companion",storyResponse:"companion",comfortResponse:"companion",festivalResponse:"companion",childhoodResponse:"companion",listeningResponse:"companion",
  caregiverNav:"caregiver",overview:"analytics",patientView:"patient",caregiverOverview:"caregiver",patientWeek:"patient",caregiverLead:"caregiver",wellnessScore:"wellness",engagementIndicator:"analytics",gamesPlayedLabel:"games",recordedSessions:"analytics",adherence:"reminders",currentRecords:"analytics",dailyStreak:"streak",consecutiveDays:"streak",sevenDayPattern:"analytics",cognitiveEngagement:"analytics",details:"analytics",sevenDayTrend:"analytics",needsAttention:"alerts",noAlerts:"alerts",encouragement:"achievements",
  memoryLibrary:"familyMemories",familyLead:"familyMemories",noFamily:"familyMemories",removeFamilyQ:"delete",familyMemory:"familyMemories",imageResizeHelp:"photo",imageTooLarge:"photo",familySaved:"save",trendsNotDiagnosis:"analytics",analyticsLead:"analytics",memory:"gameMemoryTitle",recall:"gameObjectsTitle",attention:"mood",outOf100:"wellness",sevenDayActivity:"analytics",difficultyDecisions:"difficulty",engagementScore:"analytics",reportLoading:"report",
  pleaseConfirm:"emergency",alertCaregiverQ:"emergency",yesAlert:"emergency",alertRecorded:"alerts",alertReassurance:"alerts",privateCaregiver:"caregiver",enterPin:"pin",removeSynced:"delete",itemRemoved:"delete",demoLocal:"demo",changesQueued:"sync",upToDate:"sync",syncRetry:"sync",readyInstall:"install",
  gameMemoryDescription:"gameMemoryTitle",gameObjectsDescription:"gameObjectsTitle",gameRoutineDescription:"gameRoutineTitle",gamePatternDescription:"gamePatternTitle",gameFamilyDescription:"gameFamilyTitle",gameSequenceDescription:"gameSequenceTitle",
  memoryInstruction:"gameMemoryTitle",hiddenCard:"gameMemoryTitle",rememberObjects:"gameObjectsTitle",iAmReady:"start",whichObjects:"gameObjectsTitle",checkAnswers:"complete",routineInstruction:"gameRoutineTitle",completePath:"gamePatternTitle",patternAria:"gamePatternTitle",chooseValue:"chooseNext",patternTryAgain:"back",patternComplete:"complete",addFamilyFirst:"addFamily",caregiverCanAdd:"addFamily",familyMember:"family",rememberSteps:"gameSequenceTitle",sequenceTryAgain:"back",sequenceRemembered:"complete",tileLeaf:"activity",tileSun:"activity",tileWater:"water",tileFlower:"activity",tileBird:"activity",tileMoon:"activity",tileTree:"activity",tileStar:"activity",tileHome:"home",
  patternAlternating:"gamePatternTitle",patternColours:"gamePatternTitle",patternPlant:"gamePatternTitle",patternCorners:"gamePatternTitle",patternOneTwo:"gamePatternTitle",patternSteps:"gamePatternTitle",patternWoven:"gamePatternTitle",patternDouble:"gamePatternTitle",patternTwoPaths:"gamePatternTitle",patternGaps:"gamePatternTitle",patternMirror:"gamePatternTitle",patternPairs:"gamePatternTitle"
};
export function getLanguage(){return localStorage.getItem("smritiai_language")||"en"}
export function setLanguage(c){localStorage.setItem("smritiai_language",languages[c]?c:"en");document.documentElement.lang=languages[c]?c:"en"}
export function t(k,v={},fallback){const lang=getLanguage(),alias=aliases[k];const s=dictionaries[lang]?.[k]??(alias&&dictionaries[lang]?.[alias])??(lang==="en"?(dictionaries.en[k]??fallback??k.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())):generic[lang]);return String(s).replace(/\{(\w+)\}/g,(_,n)=>v[n]??`{${n}}`)}
const stored={"Morning medicine":"medicine","Drink a glass of water":"water","Garden walk":"activity","Call Mili":"family","Mother":"family","Father":"family","Daughter":"family","Son":"family","Sister":"family","Brother":"family","Granddaughter":"family","Grandson":"family","Grandchild":"family","Friend":"friend","First Step":"achievements","First Game":"achievements","7-Day Streak":"streak","Memory Master":"gameMemoryTitle","Reminder Champion":"reminders","Consistency Hero":"achievements","No activity has been recorded for 3 days.":"alerts","Reminder adherence is below 50% this week.":"alerts","The 7-day engagement score is over 15% below the 30-day baseline.":"alerts","Emergency help was requested from the patient dashboard.":"emergency"};
export function translateValue(value){return stored[value]?t(stored[value]):value}
export function locale(){return({en:"en-IN",hi:"hi-IN",as:"as-IN",bn:"bn-IN",mni:"mni-Mtei-IN"})[getLanguage()]}
export function applyStaticTranslations(root=document){root.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));root.querySelectorAll("[data-i18n-aria]").forEach(e=>e.setAttribute("aria-label",t(e.dataset.i18nAria)));root.querySelectorAll("[data-i18n-title]").forEach(e=>e.setAttribute("title",t(e.dataset.i18nTitle)));document.title=`${t("appName")} — ${t("gentleSupport")}`}
